language: haskell
ghc: 7.10.1
env:
  - CABALVER=1.22 GHCVER=7.10.1
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.0.1
      - ghc-7.0.2
      - ghc-7.0.3
      - ghc-7.0.4
      - ghc-7.2.1
      - ghc-7.2.2
      - ghc-7.4.1
      - ghc-7.4.2
      - ghc-7.6.1
      - ghc-7.6.2
      - ghc-7.6.3
      - ghc-7.8.1
      - ghc-7.8.2
      - ghc-7.8.3
      - ghc-7.8.4
      - ghc-7.10.1
      - cabal-install-1.16
      - cabal-install-1.18
      - cabal-install-1.22
